#!/bin/sh
# Shortcut to setup the flask environment and init the database
# Created On: Sun 14 Mar 2021 04:48:09 PM CET
# Last Modified On: Sun 14 Mar 2021 04:48:09 PM CET
FLASK_APP="src/" FLASK_ENV=development flask init-db
