"""added model for posts

Revision ID: 315e694c453a
Revises: 338de0579667
Create Date: 2021-07-22 22:23:41.793291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315e694c453a'
down_revision = '338de0579667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_language_iso_code'), 'language', ['iso_code'], unique=True)
    op.create_table('type_of_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_of_post_name'), 'type_of_post', ['name'], unique=True)
    op.create_table('post',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_of_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_index(op.f('ix_type_of_post_name'), table_name='type_of_post')
    op.drop_table('type_of_post')
    op.drop_index(op.f('ix_language_iso_code'), table_name='language')
    op.drop_table('language')
    # ### end Alembic commands ###
