"""tag table

Revision ID: 338de0579667
Revises: 0a8b931970a9
Create Date: 2021-06-19 20:05:48.261441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338de0579667'
down_revision = '0a8b931970a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_value'), 'tag', ['value'], unique=True)
    op.create_table('user_tag',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tag')
    op.drop_index(op.f('ix_tag_value'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
