"""empty message

Revision ID: cd1c60d0ec55
Revises: 315e694c453a
Create Date: 2021-08-29 12:23:35.049209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1c60d0ec55'
down_revision = '315e694c453a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_type_of_post_name', table_name='type_of_post')
    op.drop_table('type_of_post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('language_id', sa.INTEGER(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_of_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_of_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_type_of_post_name', 'type_of_post', ['name'], unique=False)
    # ### end Alembic commands ###
